### ISSUE TITLE
Replace carton.lock with cpanfile.snapshot

### ISSUE THREAD

**Issue by rwstauner** [metacpan/metacpan-examples#12]
I was told that carton.lock is the old version and cpanfile.snapshot is the new format,
so we should probably migrate.

Likely steps:
- `rm carton.lock`
- `mv local local.oldlock` (so that carton starts from scratch)
- `carton install` (from inside the developer vm)
- `git rm carton.lock && git add cpanfile.snapshot`

**Comment by oalders** [comment]
Closing as we're just using the cpanfile now.  Hey @rwstauner I hope all is well!
