### ISSUE TITLE
Examples using the scrolling api fail

### ISSUE THREAD

**Issue by grr** [metacpan/metacpan-examples#18]
The following scripts use the scrolling api and they all fail:

    scripts/author/1b-scroll-all-authors-es.pl
    scripts/author/1c-scroll-all-authors-with-twitter-es.pl
    scripts/author/2-twitter-or-github-es.pl
    scripts/release/6-latest-releases-with-git-repo-es.pl
    scripts/release/7-all-releases-es.pl

Example failure message:

    # ERROR: Search::Elasticsearch::Error::Request [https://fastapi.metacpan.org:443/v1]-[500] {"message":"[Request] ** [http://127.0.0.1:9200]-[400] [illegal_argument_exception] Failed to decode scrollId, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Scroll.pm line 43. With vars: {'status_code' => 400,'body' => {'error' => {'type' => 'illegal_argument_exception','reason' => 'Failed to decode scrollId','caused_by' => {'reason' => 'Bad Base64 input character decimal 123 in array position 0','type' => 'i_o_exception'},'root_cause' => [{'reason' => 'Failed to decode scrollId','type' => 'illegal_argument_exception'}]},'status' => 400},'request' => {'path' => '/_search/scroll/%7B%22scroll_id%22%3A%22c2NhbjszOzkwNzY2NTc1Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7MTg5NTE4ODMwOjNYSTBjSE9HVEV1SkNxWkc2Y2tEWVE7MTg5NTgzNzA2OkdxSzNsYXZPUlpHdW1fQ3FfaE5ZdHc7MTt0b3RhbF9oaXRzOjEzMDk3Ow%3D%3D%22%7D','ignore' => [],'qs' => {'scroll' => '5m'},'serialize' => 'std','body' => undef,'method' => 'GET'}}\n"}

**Comment by mickeyn** [comment]
only on of those failed for me: scripts/release/6-latest-releases-with-git-repo-es.pl

I updated the script and now it runs

please pull and try and try again.

**Comment by grr** [comment]
They all repeatedly fail for me, even the script you just updated. The full output follows after.

Just a though: the error messages are always "Bad Base64 input character decimal 123 in array position 0". Decimal 123 is '{'. And manually base64-decoding the scrollId it looks like a json without the enclosing braces. Is something maybe adding enclosing braces somewhere to turn this into a valid json message?

    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working tree clean

    $ perl -Mlib scripts/release/6-latest-releases-"with-git-repo-es.pl
    # Request to: https://fastapi.metacpan.org:443/v1
    curl -XPOST 'http://localhost:9200/cpan/release/_search?_source=author%2Cdate%2Cdistribution%2Cname%2Cresources&pretty=1&scroll=5m&search_type=scan&size=500' -d '
    {
    "query" : {
        "bool" : {
            "must" : [
                {
                "term" : {
                    "resources.repository.type" : "git"
                }
                },
                {
                "term" : {
                    "status" : "latest"
                }
                },
                {
                "term" : {
                    "authorized" : "true"
                }
                }
            ]
        }
    }
    }
    '

    # Response: 200, Took: 453 ms
    # {
    #    "timed_out" : false,
    #    "_shards" : {
    #       "total" : 3,
    #       "failed" : 0,
    #       "successful" : 3
    #    },
    #    "took" : 8,
    #    "_scroll_id" : "c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw==",
    #    "hits" : {
    #       "hits" : [],
    #       "total" : 8550,
    #       "max_score" : 0
    #    }
    # }

    # Request to: https://fastapi.metacpan.org:443/v1
    curl -XPOST 'http://localhost:9200/_search/scroll?pretty=1&scroll=5m' -d '
    {
    "scroll_id" : "c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw=="
    }
    '

    # ERROR: Search::Elasticsearch::Error::Request [https://fastapi.metacpan.org:443/v1]-[500] {"message":"[Request] ** [http://127.0.0.1:9200]-[400] [illegal_argument_exception] Failed to decode scrollId, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Scroll.pm line 43. With vars: {'status_code' => 400,'request' => {'path' => '/_search/scroll/%7B%22scroll_id%22%3A%22c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw%3D%3D%22%7D','body' => undef,'ignore' => [],'method' => 'GET','qs' => {'scroll' => '5m'},'serialize' => 'std'},'body' => {'error' => {'caused_by' => {'reason' => 'Bad Base64 input character decimal 123 in array position 0','type' => 'i_o_exception'},'reason' => 'Failed to decode scrollId','root_cause' => [{'reason' => 'Failed to decode scrollId','type' => 'illegal_argument_exception'}],'type' => 'illegal_argument_exception'},'status' => 400}}\n"}
    #

    [Request] ** [https://fastapi.metacpan.org:443/v1]-[500] {"message":"[Request] ** [http://127.0.0.1:9200]-[400] [illegal_argument_exception] Failed to decode scrollId, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Scroll.pm line 43. With vars: {'status_code' => 400,'request' => {'path' => '/_search/scroll/%7B%22scroll_id%22%3A%22c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw%3D%3D%22%7D','body' => undef,'ignore' => [],'method' => 'GET','qs' => {'scroll' => '5m'},'serialize' => 'std'},'body' => {'error' => {'caused_by' => {'reason' => 'Bad Base64 input character decimal 123 in array position 0','type' => 'i_o_exception'},'reason' => 'Failed to decode scrollId','root_cause' => [{'reason' => 'Failed to decode scrollId','type' => 'illegal_argument_exception'}],'type' => 'illegal_argument_exception'},'status' => 400}}\n"}, called from sub Search::Elasticsearch::Client::5_0::Scroll::next at scripts/release/6-latest-releases-with-git-repo-es.pl line 31. With vars: {'status_code' => 500,'request' => {'mime_type' => 'application/json','method' => 'POST','ignore' => [],'serialize' => 'std','body' => {'scroll_id' => 'c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw=='},'qs' => {'scroll' => '5m'},'path' => '/_search/scroll'}}
    # Request to: https://fastapi.metacpan.org:443/v1
    curl -XDELETE 'http://localhost:9200/_search/scroll?pretty=1' -d '
    {
    "scroll_id" : "c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw=="
    }
    '

    # ERROR: Search::Elasticsearch::Error::Request [https://fastapi.metacpan.org:443/v1]-[500] {"message":"[Request] ** [http://127.0.0.1:9200]-[400] [parse_exception] Failed to parse setting [scroll] with value [] as a time value: unit is missing or unrecognized, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Scroll.pm line 43. With vars: {'body' => {'status' => 400,'error' => {'type' => 'parse_exception','reason' => 'Failed to parse setting [scroll] with value [] as a time value: unit is missing or unrecognized','root_cause' => [{'reason' => 'Failed to parse setting [scroll] with value [] as a time value: unit is missing or unrecognized','type' => 'parse_exception'}]}},'request' => {'method' => 'GET','qs' => {'scroll' => ''},'serialize' => 'std','ignore' => [],'body' => undef,'path' => '/_search/scroll/%7B%22scroll_id%22%3A%22c2NhbjszOzkxNjM1NDg2Ol9qUEdZMWw5U0xtaU1FZXZFU3ZUUWc7OTE2MzU0ODU6X2pQR1kxbDlTTG1pTUVldkVTdlRRZzs5MTYzNTQ4NzpfalBHWTFsOVNMbWlNRWV2RVN2VFFnOzE7dG90YWxfaGl0czo4NTUwOw%3D%3D%22%7D'},'status_code' => 400}\n"}
    #

**Comment by mickeyn** [comment]
what version of Search::Elasticsearch do you have installed?

**Comment by grr** [comment]
5.02

**Comment by grr** [comment]
They work if I downgrade to 5.01.

**Comment by mickeyn** [comment]
it's probably it. we use 2.03 and all our code was written for it. we don't use ES 5.x

**Comment by mickeyn** [comment]
that's good, but i can't guarantee anything working with 5.x

**Comment by mickeyn** [comment]
i assume this can be closed. please reopen if there's anything else in this matter.
