### ISSUE TITLE
Need New Example for Listing Distributions

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-examples#3]
Two years ago, @oalders [posted an example listing author distributions](http://blogs.perl.org/users/olaf_alders/2011/05/pgxn-vs-metacpan.html). It no longer works; I assume the API has changed since then. It would be useful to have a canonical example that people can find and modify, for example to list their distributions on their blogs.

**Comment by mickeyn** [comment]
I guess this one is old enough to close.
see `MetaCPAN::Client` and latest API docs for solutions if still relevant.
