### ISSUE TITLE
can you use /favorite as an URL

### ISSUE THREAD

**Issue by kevindawson** [metacpan/metacpan-examples#4]
I found: https://metacpan.org/favorite/leaderboard

and it's cohort: https://metacpan.org/favorite/recent

when I went to: https://metacpan.org/favorite/

looking for more options, it was blank

I was looking for a list of users who had clicked favorite on a dist

**Comment by kelleytaylor2021** [comment]
https://www.github.com/metacpan/metacpan-examples/tree/master/scripts%2Fauthor%2F1-fetch-single-author-es.pl

**Comment by mickeyn** [comment]
user details is not public info. you can get statistical data using our supported API & tools (e.g. `MetaCPAN::Client`)
